using ValueObject.SourceGenerator.Models;

namespace ValueObject.SourceGenerator.Emitters;

internal static class EfCoreModelBuilderEmitter
{
    public static void Emit(SourceProductionContext ctx, List<EntityValueObjectProperty> entityProps)
    {
        if(!entityProps.Any()) return;

        // Group by namespace first
        var groupedByNamespace = entityProps.GroupBy(x => x.EntityNamespace);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Metadata.Builders;");
        sb.AppendLine();
        
        foreach (var namespaceGroup in groupedByNamespace)
        {
            var ns = namespaceGroup.Key;
            if (ns != null)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }
            
            sb.AppendLine("public static class ValueObjectEfCoreExtensions");
            sb.AppendLine("{");
            
            // Generate one method per entity within this namespace
            var entitiesInNamespace = namespaceGroup.GroupBy(x => x.EntityName);
            foreach (var entityGroup in entitiesInNamespace)
            {
                var entityName = entityGroup.Key;
                sb.AppendLine($"    public static void ConfigureValueObjectProperties(this EntityTypeBuilder<{entityName}> entity)");
                sb.AppendLine("    {");
                foreach (var prop in entityGroup)
                {
                    var converterType = prop.IsNullable ? $"{prop.ValueObjectTypeName}NullableValueConverter" : $"{prop.ValueObjectTypeName}ValueConverter";
                    sb.AppendLine($"        entity.Property(e => e.{prop.PropertyName}).HasConversion(new {converterType}());");
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            
            sb.AppendLine("}");
        }
        ctx.AddSource("ValueObjectEfCoreExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
