using ValueObject.SourceGenerator.Models;

namespace ValueObject.SourceGenerator.Emitters;

internal static class MongoDbClassMapEmitter
{
    public static void Emit(SourceProductionContext ctx, IEnumerable<VoCandidate> vos)
    {
        // Only consider VOs with supported underlying types (i.e., serializers are generated)
        var supported = vos.Where(v => IsSupportedUnderlying(v.TvDisplay)).ToArray();
        if (supported.Length == 0) return;

        // Group by VO namespace and generate one registration helper per namespace
        var byNs = supported.GroupBy(v => v.Namespace, StringComparer.Ordinal);
        foreach (var grp in byNs)
        {
            var ns = grp.Key; // may be null (global namespace)
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using MongoDB.Bson.Serialization;");
            sb.AppendLine();

            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine("public static class MongoClassMaps");
            sb.AppendLine("{");

            // Per-VO registration methods
            foreach (var vo in grp.OrderBy(v => v.TypeName, StringComparer.Ordinal))
            {
                sb.AppendLine($" public static void Register{vo.TypeName}ClassMap()");
                sb.AppendLine(" {");
                sb.AppendLine($" BsonSerializer.RegisterSerializer(new {vo.TypeName}Serializer());");
                sb.AppendLine(" }");
                sb.AppendLine();
            }

            // Convenience method to register all serializers in this namespace
            sb.AppendLine(" public static void RegisterAll()");
            sb.AppendLine(" {");
            foreach (var vo in grp.OrderBy(v => v.TypeName, StringComparer.Ordinal))
            {
                sb.AppendLine($" Register{vo.TypeName}ClassMap();");
            }
            sb.AppendLine(" }");

            sb.AppendLine("}");

            var hint = ns is null ? "Global" : ns.Replace('.', '_');
            ctx.AddSource($"MongoClassMaps_{hint}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static bool IsSupportedUnderlying(string tv)
    => tv switch
    {
        "global::MongoDB.Bson.ObjectId" => true,
        "global::System.String" => true,
        "global::System.Int32" => true,
        "global::System.Int64" => true,
        "global::System.Double" => true,
        "global::System.Decimal" => true,
        "global::System.Boolean" => true,
        "global::System.Guid" => true,
        "global::System.Byte[]" => true,
        "global::System.DateTime" => true,
        _ => false
    };
}
